---
- name: Deploy titorelli
  hosts: titorelli
  remote_user: root
  tasks:
    - name: Copy Caddyfile
      ansible.builtin.template:
        src: Caddyfile
        dest: "/etc/caddy/Caddyfile"
    - name: Pull the code
      ansible.builtin.git:
        repo: "{{repository_url}}"
        dest: "{{root_dir}}"
    - name: Install monorepo dependencies
      community.general.npm:
        path: "{{root_dir}}"
    - name: Copy service env
      ansible.builtin.template:
        src: service/.env.j2
        dest: "{{root_dir}}/service/.env"
    - name: Copy service oauth clients
      ansible.builtin.template:
        src: service/oauth-clients.yaml.j2
        dest: "{{root_dir}}/service/oauth-clients.yaml"
    - name: Copy console env
      ansible.builtin.template:
        src: console/.env.j2
        dest: "{{root_dir}}/console/.env"
    - name: Migrate console db
      ansible.builtin.shell:
        cmd: npx prisma migrate dev
        chdir: "{{root_dir}}"
    - name: Restart service
      ansible.builtin.shell:
        cmd: pm2 restart titorelli-service
        chdir: "{{root_dir}}"
    - name: Restart caddy
      ansible.builtin.systemd:
        name: caddy
        state: restarted
